# Generated by Django 4.1.5 on 2023-01-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_orderdetails_options_alter_order_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='product_type',
            new_name='name',
        ),
    ]
