# Generated by Django 4.1.5 on 2023-01-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='stock',
            new_name='qty',
        ),
    ]
