# Generated by Django 4.1.5 on 2023-01-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_productcategory_products_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
