# Generated by Django 4.1.5 on 2023-01-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_remove_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
