# Generated by Django 4.1.5 on 2023-01-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_products_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
