# Generated by Django 4.1.5 on 2023-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_alter_orderdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Keranjang'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Produk kategori'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Produk'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name_plural': 'Produk tipe'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
